title: MAJID JANGANI
description: Modelling Probability Of Default For Banks
show_downloads: true
theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
plugins:
  - jekyll-remote-theme
permalink: /:title/
baseurl: "/Credit-Risk-Modelling"
